name: Test Execution Chunk (Reusable)

on:
  workflow_call:
    inputs:
      test-cases:
        description: 'JSON array of test cases to run in this chunk'
        required: true
        type: string
      python-versions:
        description: 'JSON array of Python versions to test'
        required: true
        type: string
      chunk-id:
        description: 'Chunk identifier for organization'
        required: true
        type: number
    secrets:
      APICEXT_TEST_AZURE_CLIENT_ID:
        required: true
      APICEXT_TEST_AZURE_TENANT_ID:
        required: true
      APICEXT_TEST_AZURE_SUBSCRIPTION_ID:
        required: true
      USERASSIGNED_IDENTITY:
        required: true
      AWS_ACCESS_KEY_LINK:
        required: true
      AWS_SECRET_ACCESS_KEY_LINK:
        required: true

jobs:
  test-chunk:
    runs-on: ubuntu-latest
    environment: engineering
    strategy:
      fail-fast: false
      matrix:
        test-case: ${{ fromJson(inputs.test-cases) }}
        python-version: ${{ fromJson(inputs.python-versions) }}
    name: ${{ matrix.test-case }} (Python ${{ matrix.python-version }})
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APICEXT_TEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APICEXT_TEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APICEXT_TEST_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Clone azure-cli-extensions repository
        run: |
          git clone https://github.com/blackchoey/azure-cli-extensions.git
          cd azure-cli-extensions
          git checkout main

      - name: Setup development environment
        run: |
          cd azure-cli-extensions
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install azdev
          azdev setup -r .
          azdev extension add apic-extension

      - name: Execute test case
        run: |
          test_case='${{ matrix.test-case }}'
          python_version='${{ matrix.python-version }}'
          chunk_id='${{ inputs.chunk-id }}'

          echo "=========================================="
          echo "Running: $test_case (Python $python_version)"
          echo "Chunk: $chunk_id"
          echo "=========================================="

          cd azure-cli-extensions
          source .venv/bin/activate

          # Run the specific test case
          if [ "$test_case" = "full-suite" ]; then
            echo "Running full test suite..."
            if azdev test apic-extension --discover --live; then
              echo "✅ PASSED: $test_case (Python $python_version)"
            else
              echo "❌ FAILED: $test_case (Python $python_version)"
              exit 1
            fi
          else
            echo "Running individual test case: $test_case"
            if azdev test azext_apic-extension $test_case --discover --live; then
              echo "✅ PASSED: $test_case (Python $python_version)"
            else
              echo "❌ FAILED: $test_case (Python $python_version)"
              exit 1
            fi
          fi

          echo "Completed: $test_case (Python $python_version)"
        env:
          USERASSIGNED_IDENTITY: ${{ secrets.USERASSIGNED_IDENTITY }}
          AWS_ACCESS_KEY_LINK: ${{ secrets.AWS_ACCESS_KEY_LINK }}
          AWS_SECRET_ACCESS_KEY_LINK: ${{ secrets.AWS_SECRET_ACCESS_KEY_LINK }}
