codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        target: auto # require coverage equal or more than current
        if_ci_failed: error #success, failure, error, ignore

ignore:
  - "src/test/**"

comment:
  layout: "reach, diff, flags, files"
