# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
prompts:
  - file://prompts.txt
providers:
  - id: file://customProvider.ts
    label: "My custom provider"
nunjucksFilters:
  allcaps: ./allcaps.js
tests:
  - vars:
      language: French
      body: Hello world
  - vars:
      language: French
      body: I'm hungry
