// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
export const APICenterRestAPIs = {
    GetAPIService: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}?api-version=${restApiVersion}`,
    ListAPIs: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis?api-version=${restApiVersion}`,
    GetAPIEnvironments: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/environments?api-version=${restApiVersion}`,
    GetAPIVersions: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/versions?api-version=${restApiVersion}`,
    GetAPIDeployments: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/deployments?api-version=${restApiVersion}`,
    GetAPIDefinition: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, apiVersion: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/versions/${apiVersion}/definitions?api-version=${restApiVersion}`,
    GetRulesetConfig: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/staticAnalyzers/spectral?api-version=${restApiVersion}`,

    CreateAPI: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}?api-version=${restApiVersion}`,
    CreateAPIVersion: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, apiVersion: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/versions/${apiVersion}?api-version=${restApiVersion}`,
    CreateAPIDeployment: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, deploymentName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/deployments/${deploymentName}?api-version=${restApiVersion}`,
    CreateAPIDefinition: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, apiVersion: string, definationName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/versions/${apiVersion}/definitions/${definationName}?api-version=${restApiVersion}`,
    CreateRulesetConfig: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/staticAnalyzers/spectral?api-version=${restApiVersion}`,


    ImportAPISpecification: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, apiVersion: string, definationName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/versions/${apiVersion}/definitions/${definationName}/importSpecification?api-version=${restApiVersion}`,
    ExportApiSpecification: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, apiName: string, apiVersion: string, definationName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/apis/${apiName}/versions/${apiVersion}/definitions/${definationName}/exportSpecification?api-version=${restApiVersion}`,

    ImportRuleset: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/staticAnalyzers/spectral/importRuleset?api-version=${restApiVersion}`,
    ExportRuleset: (subscriptionId: string, resourceGroupName: string, apiCenterName: string, restApiVersion: string) => `https://management.azure.com/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ApiCenter/services/${apiCenterName}/workspaces/default/staticAnalyzers/spectral/exportRuleset?api-version=${restApiVersion}`,
};

export const APICenterDataPlaneRestAPIs = {
}
