# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
prompts:
  - id: file://../../src/prompts/generateRuleFromPrompt.ts

providers:
  - id: azure:chat:gpt-4o
    config:
      apiHost: "apicevaluationtestai.openai.azure.com"
      maxtoken: 15000

tests:
  - vars:
      userprompt: "All resources in a response should have an `id` and `created_at` property"
    assert:
      - type: javascript
        value: file://testcase.mjs
        config:
          hits:
            {
              "callback-example.yaml":
                [
                  [
                    "paths",
                    "/doStreams",
                    "post",
                    "responses",
                    "200",
                    "content",
                    "application/json",
                    "schema",
                    "properties",
                    "subscriptionId",
                  ],
                  [
                    "paths",
                    "/stream/{id}",
                    "get",
                    "responses",
                    "200",
                    "content",
                    "application/json",
                    "schema",
                    "properties",
                    "timestamp",
                  ],
                  [
                    "paths",
                    "/stream/{id}",
                    "get",
                    "responses",
                    "200",
                    "content",
                    "application/json",
                    "schema",
                    "properties",
                    "userData",
                  ],
                ],
              "petstore.yaml":
                [
                  ["components", "schemas", "Pet", "properties", "name"],
                  ["components", "schemas", "Pet", "properties", "tag"],
                  ["components", "schemas", "Pet", "properties", "time"],
                  ["components", "schemas", "Error", "properties", "code"],
                  ["components", "schemas", "Error", "properties", "message"],
                ],
            }
          score: 1
  - vars:
      userprompt: "POST requests should return a 201 or 202 status on success instead of 200."
    assert:
      - type: javascript
        value: file://testcase.mjs
        config:
          hits:
            {
              "callback-example.yaml":
                [["paths", "/doStreams", "post", "responses", "200"]],
              "petstore.yaml": [["paths", "/pets", "post", "responses", "200"]],
            }
          score: 1

  - vars:
      userprompt: "GET requests that have an ID at the end of their path (ie /teams/{teamID}) should define a 404."
    assert:
      - type: javascript
        value: file://testcase.mjs
        config:
          hits:
            {
              "callback-example.yaml":
                [["paths", "/stream/{id}", "get", "responses"]],
              "petstore.yaml":
                [["paths", "/pets/{pet-id}", "get", "responses"]],
            }
          score: 0.5
