name: "CD"
run-name: CD-${{ github.ref_name }}-${{ github.run_id }}-isPreview-${{ inputs.preview }}
on:
  workflow_dispatch:
    inputs:
      release:
        description: "replace AI key for release"
        required: true
        type: boolean
        default: false
      preview:
        description: "generate prerelease vsix?"
        required: true
        type: boolean
        default: false
      tag:
        description: "want to push tag to origin?"
        required: false
        type: boolean
        default: false

  schedule:
    - cron: "0 16 * * *"

jobs:
  CD:
    permissions:
      actions: read
      contents: write
      id-token: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: lts/*

      - uses: jossef/action-set-json-field@6e6d7e639f24b3955ef682815317b5613ac6ca12 # v1
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.release == 'true' || github.ref == 'refs/heads/main') }}
        with:
          file: ./package.json
          field: aiKey
          value: ${{ secrets.PUBLIC_AIKEY }}

      - name: update visx for preview
        if: ${{ github.event.inputs.preview == 'true'}}
        run: |
          VERSION=$(jq -r .version ./package.json)
          echo '----------------- current version:' $VERSION
          MINOR_VER=$(echo $VERSION | awk -F. '{print $2}')
          DATE_WITH_TIME=`date "+%Y%m%d%H"`
          if [ $((MINOR_VER%2)) -eq 0 ]; then
            VERSION=$(echo ${VERSION%-*} | awk -v val=$DATE_WITH_TIME -F. '/[0-9]+\./{$2++;$3=val;print}' OFS=.)
          else
            VERSION=$(echo ${VERSION%-*} | awk -v val=$DATE_WITH_TIME -F. '/[0-9]+\./{$3=val;print}' OFS=.)
          fi
          echo '----------------- prerelease version:' $VERSION
          jq --arg VERSION "$VERSION" '.version=$VERSION' package.json > tmp.$$.json
          mv tmp.$$.json package.json

      - name: Build visx
        run: |
          npm install --ignore-scripts
          if [ "${{ github.event.inputs.preview }}" == "true" ]; then
            npx @vscode/vsce package --no-dependencies --pre-release --githubBranch ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          else
            npx @vscode/vsce package --no-dependencies --githubBranch ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          fi

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release
          path: |
            *.vsix
            package.json

      - name: get package version
        id: package-version
        run: |
          echo "version=$(jq -r '"v"+.version' package.json)" >> $GITHUB_OUTPUT

      - uses: piszmog/create-tag@9780feb0f3cc67c7affcbd87b4b3e22036291cf4 # v1.2.2
        if: ${{ github.event.inputs.tag == 'true'}}
        with:
          version: ${{ steps.package-version.outputs.version }}
          message: "release ${{ steps.package-version.outputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
