name: Test Execution All Cases (Reusable)

on:
  workflow_call:
    inputs:
      test-cases:
        description: 'JSON array of all test cases to run'
        required: true
        type: string
      python-version:
        description: 'Single Python version to test with'
        required: true
        type: string
    secrets:
      APICEXT_TEST_AZURE_CLIENT_ID:
        required: true
      APICEXT_TEST_AZURE_TENANT_ID:
        required: true
      APICEXT_TEST_AZURE_SUBSCRIPTION_ID:
        required: true
      USERASSIGNED_IDENTITY:
        required: true
      AWS_ACCESS_KEY_LINK:
        required: true
      AWS_SECRET_ACCESS_KEY_LINK:
        required: true

jobs:
  test-all-cases:
    runs-on: ubuntu-latest
    environment: engineering
    strategy:
      fail-fast: false
      matrix:
        test-case: ${{ fromJson(inputs.test-cases) }}
    name: ${{ matrix.test-case }} (Python ${{ inputs.python-version }})
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APICEXT_TEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APICEXT_TEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APICEXT_TEST_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Clone azure-cli-extensions repository
        run: |
          git clone https://github.com/blackchoey/azure-cli-extensions.git
          cd azure-cli-extensions
          git checkout frank/for-pipeline-test

      - name: Setup development environment
        run: |
          cd azure-cli-extensions
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install azdev
          azdev setup -r .
          azdev extension add apic-extension

      - name: Execute test case
        run: |
          test_case='${{ matrix.test-case }}'
          python_version='${{ inputs.python-version }}'

          echo "=========================================="
          echo "Running: $test_case (Python $python_version)"
          echo "=========================================="

          cd azure-cli-extensions
          source .venv/bin/activate
          # Run the specific test case
          test_result="FAILED"
          test_start_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          if [ "$test_case" = "full-suite" ]; then
            echo "Running full test suite..."
            # Capture both output and exit code
            set +e  # Don't exit on command failure
            test_output=$(azdev test apic-extension --discover --live 2>&1)
            test_exit_code=$?
            set -e  # Re-enable exit on error

            echo "Test output:"
            echo "$test_output"
            echo "Exit code: $test_exit_code"

            # Check both exit code and output for failure indicators
            if [ $test_exit_code -eq 0 ] && ! echo "$test_output" | grep -i -E "(failed|error|FAIL)" > /dev/null; then
              test_result="PASSED"
            else
              test_result="FAILED"
            fi
          else
            echo "Running individual test case: $test_case"
            # Capture both output and exit code
            set +e  # Don't exit on command failure
            test_output=$(azdev test azext_apic-extension $test_case --discover --live 2>&1)
            test_exit_code=$?
            set -e  # Re-enable exit on error

            echo "Test output:"
            echo "$test_output"
            echo "Exit code: $test_exit_code"

            # Check both exit code and output for failure indicators
            if [ $test_exit_code -eq 0 ] && ! echo "$test_output" | grep -i -E "(failed|error|FAIL)" > /dev/null; then
              test_result="PASSED"
            else
              test_result="FAILED"
            fi
          fi

          test_end_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          # Output result to centralized location
          echo "Test result: $test_result for $test_case (Python $python_version)"
          if [ "$test_result" = "PASSED" ]; then
            echo "✅ PASSED: $test_case (Python $python_version)"
          else
            echo "❌ FAILED: $test_case (Python $python_version)"
          fi
          echo "Completed: $test_case (Python $python_version)"
          # Write result to a file that will be uploaded as artifact
          # Create the results directory in the workspace root (not inside azure-cli-extensions)
          cd "$GITHUB_WORKSPACE"
          mkdir -p test-results
          result_file="test-results/result-${python_version}-$(echo "$test_case" | tr '/' '_' | tr ' ' '_').json"
          cat > "$result_file" << EOF
          {
            "test_case": "$test_case",
            "python_version": "$python_version",
            "result": "$test_result",
            "start_time": "$test_start_time",
            "end_time": "$test_end_time",
            "job_id": "${{ github.job }}"
          }
          EOF

          echo "Result written to $result_file"
          echo "File exists check: $(ls -la "$result_file" 2>/dev/null || echo 'File not found')"

          # Exit with error if test failed (after we've collected and saved the result)
          if [ "$test_result" = "FAILED" ]; then
            echo "❌ Exiting with error code 1 due to test failure"
            exit 1
          fi
        env:
          USERASSIGNED_IDENTITY: ${{ secrets.USERASSIGNED_IDENTITY }}
          AWS_ACCESS_KEY_LINK: ${{ secrets.AWS_ACCESS_KEY_LINK }}
          AWS_SECRET_ACCESS_KEY_LINK: ${{ secrets.AWS_SECRET_ACCESS_KEY_LINK }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests failed
        with:
          name: test-results-python-${{ inputs.python-version }}-${{ matrix.test-case }}
          path: test-results/
          retention-days: 1

    outputs:
      test-case: ${{ matrix.test-case }}
      python-version: ${{ inputs.python-version }}
