name: Test Execution All Cases (Reusable)

on:
  workflow_call:
    inputs:
      test-cases:
        description: 'JSON array of all test cases to run'
        required: true
        type: string
      python-version:
        description: 'Single Python version to test with'
        required: true
        type: string
    secrets:
      APICEXT_TEST_AZURE_CLIENT_ID:
        required: true
      APICEXT_TEST_AZURE_TENANT_ID:
        required: true
      APICEXT_TEST_AZURE_SUBSCRIPTION_ID:
        required: true
      USERASSIGNED_IDENTITY:
        required: true
      AWS_ACCESS_KEY_LINK:
        required: true
      AWS_SECRET_ACCESS_KEY_LINK:
        required: true

jobs:
  test-all-cases:
    runs-on: ubuntu-latest
    environment: engineering
    strategy:
      fail-fast: false
      matrix:
        test-case: ${{ fromJson(inputs.test-cases) }}
    name: ${{ matrix.test-case }} (Python ${{ inputs.python-version }})
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APICEXT_TEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APICEXT_TEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APICEXT_TEST_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Clone azure-cli-extensions repository
        run: |
          git clone https://github.com/blackchoey/azure-cli-extensions.git
          cd azure-cli-extensions
          git checkout frank/for-pipeline-test

      - name: Setup development environment
        run: |
          cd azure-cli-extensions
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install azdev
          azdev setup -r .
          azdev extension add apic-extension

      - name: Execute test case
        run: |
          test_case='${{ matrix.test-case }}'
          python_version='${{ inputs.python-version }}'

          echo "=========================================="
          echo "Running: $test_case (Python $python_version)"
          echo "=========================================="

          cd azure-cli-extensions
          source .venv/bin/activate

          # Run the specific test case
          if [ "$test_case" = "full-suite" ]; then
            echo "Running full test suite..."
            azdev test apic-extension --discover --live
          else
            echo "Running individual test case: $test_case"
            azdev test azext_apic-extension $test_case --discover --live
          fi

          echo "✅ PASSED: $test_case (Python $python_version)"
          echo "Completed: $test_case (Python $python_version)"
        env:
          USERASSIGNED_IDENTITY: ${{ secrets.USERASSIGNED_IDENTITY }}
          AWS_ACCESS_KEY_LINK: ${{ secrets.AWS_ACCESS_KEY_LINK }}
          AWS_SECRET_ACCESS_KEY_LINK: ${{ secrets.AWS_SECRET_ACCESS_KEY_LINK }}

    outputs:
      test-case: ${{ matrix.test-case }}
      python-version: ${{ inputs.python-version }}
